[uplink-10-UplinkMessageName]
one_bit = 1
another = 1
bit = 1
two_bits = 2
three = 3
one_byte = 8

[uplink-11-SecondUplinkName]
some = 1
field = 1
name = 1
goes = 2
here = 3

[downlink-10-DownlinkMessageName]
some = 1
field = 1
name = 1
goes = 2
here = 3